title: ðŸ§˜â€â™‚ï¸ Gnosis Blog
repository: "https://github.com/francescobianco/gnosis.yafb.net"
remote_theme: francescobianco/jekyll-html-pages@main
author: "F.Bianco"

paginate: 5

exclude:
  - README.md
  
navigation:
  - title: Home
    url: /
  - title: Source code
    url: https://github.com/francescobianco/gnosis.yafb.net
    target: _blank
  - title: Write new post
    url: /new.html
    target: _blank

custom_head: >
  <meta name="sa-verify" content="gnosisyafbpaqlyreonyqtu" />
