title: üßò‚Äç‚ôÇÔ∏è Gnosis Blog
repository: "https://github.com/francescobianco/gnosis.yafb.net"
remote_theme: francescobianco/jekyll-html-pages@main
author: "F.Bianco"

paginate: 5

exclude:
  - README.md
  
navigation:
  - title: Home
    url: /
  - title: Source code
    url: https://github.com/francescobianco/gnosis.yafb.net
  - title: Write new post
    url: /new.html
    target: _blank
